### ISSUE TITLE
`run.finalize()` lock `Timeout` and `aimrocks` `RocksIOError`

### ISSUE THREAD

**Issue by flaviuvadan** [aimhubio/aim#1115]
## 🐛 Bug

I have the following setup:
- an Aim K8S deployment. This deployment runs a single pod, with Aim being the only container, which also mounts a shared persistent volume in GCP (call it **V**). Aim instantiates a repo at path `/aim`
- Argo Workflows, which I use to run parallel model training jobs. Argo spins up hundreds of pods, one per job. Each pod mounts the same volume **V**. The training script instantiates an Aim `Run` with a `Repo` set to the same path as above - `/aim`

After 50+ jobs spin up and finish training they run `run.finalize()`. This ends up occasionally throwing the following two exceptions, with full stack trace:
```shell
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/site-packages/aim/ext/cleanup/__init__.py", line 80, in _cleanup
    finalizer()
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/weakref.py", line 572, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/site-packages/aim/sdk/run.py", line 89, in _close
    self.finalize_run()
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/site-packages/aim/sdk/run.py", line 69, in finalize_run
    from_union=False).view(b'')
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/site-packages/aim/sdk/repo.py", line 240, in _get_container
    container = RocksContainer(path, read_only=read_only)
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/site-packages/aim/storage/rockscontainer.py", line 103, in __init__
    self.writable_db
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/site-packages/aim/storage/rockscontainer.py", line 148, in writable_db
    db = self.db
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/site-packages/aim/storage/rockscontainer.py", line 138, in db
    self._lock.acquire()
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/site-packages/filelock/_api.py", line 173, in acquire
    raise Timeout(self._lock_file)
filelock._error.Timeout: The file lock '/aim/.aim/locks/index' could not be acquired.
```
and
```shell
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/site-packages/aim/ext/cleanup/__init__.py", line 80, in _cleanup
    finalizer()
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/weakref.py", line 572, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/site-packages/aim/sdk/run.py", line 89, in _close
    self.finalize_run()
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/site-packages/aim/sdk/run.py", line 69, in finalize_run
    from_union=False).view(b'')
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/site-packages/aim/sdk/repo.py", line 240, in _get_container
    container = RocksContainer(path, read_only=read_only)
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/site-packages/aim/storage/rockscontainer.py", line 103, in __init__
    self.writable_db
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/site-packages/aim/storage/rockscontainer.py", line 148, in writable_db
    db = self.db
  File "/root/.pyenv/versions/3.7.4/lib/python3.7/site-packages/aim/storage/rockscontainer.py", line 142, in db
    read_only=self.read_only)
  File "src/aimrocks/_rocksdb.pyx", line 1671, in aimrocks._rocksdb.DB.__cinit__
  File "src/aimrocks/_rocksdb.pyx", line 88, in aimrocks._rocksdb.check_status
aimrocks.errors.RocksIOError: b'IO error: While lock file: /aim/.aim/meta/index/LOCK: Resource temporarily unavailable'" 
```

My temporary workaround is: 
```python
retries = 10  # __should__ be enough
for i in range(retries):
    try:
        run.finalize()
        break
    except Exception as e:
        logging.error(f'Caught exception finalizing Aim run, retrying. Exception: {str(e)}')
        time.sleep(i ** 2)
```

### To reproduce

Instantiate multiple `Run` instances using the same `Repo` configuration (same path) and issue `run.finalize()` calls within short time intervals of one another.

### Expected behavior

Two options:
* `finalize` should either document that it raises such exceptions so clients can catch them and implement their own retry with backoff mechanism
* `finalize` should implement its own retry and offer users control over that behavior

### Environment

- Aim v3.2.0
- Python 3.7
- pip 21.2.4
- Ubuntu 18.04
- running in Docker containers on K8S 1.21.5-gke.1302 (GCP/GKE)

### Additional context

Aim Slack workspace initial [report](https://aimstack.slack.com/archives/C01DK8FM2P3/p1639058858076000).

Included exception class names in the Issue title so it's easily searchable in the future using GitHub search syntax `RocksIOError in:title` 🙂

**Comment by alberttorosyan** [comment]
@flaviuvadan since indexing run data is an optimization for runs/metrics queries we can skip this step under some circumstances.
With many parallel runs current 10 seconds timeout is often not sufficient. We decided to increase it to 120 seconds and provide environment variable to increase/decrease it. More context can be found in [PR](#1120) description.

**Comment by gorarakelyan** [comment]
@flaviuvadan just shipped patch release(`3.2.2`) with the timeout adjustment. Could you please try it out and check if it works as expected? Thanks a lot 🙌

**Comment by gorarakelyan** [comment]
@flaviuvadan have you had any chance to test it out? Does it work properly now?

**Comment by flaviuvadan** [comment]
> @flaviuvadan have you had any chance to test it out? Does it work properly now?

I did not notice any of our exception blocks for `finalize()` logging so looking good on my end! Let's close this as `Fixed` and will report back if I notice anything with further increases in scale 🙂 again, thank you for fixing this!
