### ISSUE TITLE
UnauthorizedRequestError when using multiple loggers on PL with remote  AIM server

### ISSUE THREAD

**Issue by mikel-brostrom** [aimhubio/aim#1297]
## 🐛 Bug

My trainer

```python
trainer = pl.Trainer(
        logger=[tb_logger, aim_logger],
)
```

My training step:

```python
def training_step(self, batch, batch_idx):
        #loss = self.shared_step(batch, metric_name="train_loss")
        t0, t1, mask_gt = batch
        mask_pred = self.forward(t0, t1)

        loss = self.criterion(mask_pred, mask_gt.long())
        metrics = {
            'train_loss': loss,
        }

        self.log_dict(metrics, logger=False, on_step=False, on_epoch=True, prog_bar=True, rank_zero_only=True)
        self.logger[1].log_metrics({'train_loss1': loss, 'train_loss1': loss})

        return loss
```

crashes:

```bash
0207 14:42:36.177987824   17936 chttp2_transport.cc:1111]   Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"                                        | 4/6 [00:01<00:00,  4.07it/s]
E0207 14:42:36.178162323   17936 client_channel.cc:647]      chand=0x8fc9e40: Illegal keepalive throttling value 9223372036854775807
Traceback (most recent call last):
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1319, in _run_train
    self.fit_loop.run()
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/loops/base.py", line 146, in run
    self.on_advance_end()
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 242, in on_advance_end
    self._run_validation()
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 337, in _run_validation
    self.val_loop.run()
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 122, in advance
    output = self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 217, in _evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/accelerators/accelerator.py", line 236, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 444, in validation_step
    return self.model(*args, **kwargs)
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/overrides/base.py", line 92, in forward
    output = self.module.validation_step(*inputs, **kwargs)
  File "/work/home/mikel/scd/scd/architectures/tanet_arch/tanet.py", line 135, in validation_step
    self.logger[1].log_metrics(metrics, self.current_epoch)
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py", line 50, in wrapped_fn
    return fn(*args, **kwargs)
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/aim/sdk/adapters/pytorch_lightning.py", line 99, in log_metrics
    self.experiment.track(v, name=name, context=context)
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/aim/sdk/run.py", line 412, in track
    self._track_impl(value, track_time, name, step, epoch, context=context)
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/aim/sdk/run.py", line 445, in _track_impl
    self.meta_run_tree['traces', ctx.idx, name, 'last'] = val
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/aim/storage/treeviewproxy.py", line 187, in __setitem__
    self.tree[self.absolute_path(path)] = value
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/aim/storage/treeviewproxy.py", line 83, in __setitem__
    self._rpc_client.run_instruction(self._handler, '__setitem__', (path, value))
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/aim/ext/transport/client.py", line 66, in run_instruction
    status_msg = next(resp)
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/work/home/mikel/venvs/scd/lib/python3.6/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Broken pipe"
        debug_error_string = "{"created":"@1644244955.352788922","description":"Error received from peer ipv4:127.0.0.1:53800","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"Broken pipe","grpc_status":14}"
>

During handling of the above exception, another exception occurred:
...
```

### Environment

- Aim Version: 3.5.0
- Python version: 3.6.9
- pip version: 21.3.0
- Linux 18.04

**Comment by mikel-brostrom** [comment]
Yes, this a blocker. Could you reproduce the error? Let me know if you need more information

**Comment by mihran113** [comment]
> Yes, it is a blocker. Could you reproduce the error? Let me know if you need more information

Unfortunately I couldn't reproduce it. Does this happen only when using multiple loggers or it happens even when using Aim as the only logger?

**Comment by mikel-brostrom** [comment]
I just tried it out, it does happen with Aim as the only logger as well when logging remotely.

**Comment by mikel-brostrom** [comment]
I tried this example: https://github.com/aimhubio/aim/blob/main/examples/pytorch_lightning_track.py
Adding the `repo` argument in AimLogger as `repo='aim://xx.xx.xx.xx:53800'`

**Comment by mihran113** [comment]
Strange. I tried the same setup with the same example, works for me fine. Can I ask if you do have any other clients logging at the same time or is it just one client?

**Comment by mihran113** [comment]
Hi @mikel-brostrom. I still cannot reproduce this issue. Would you mind to join [aim community slack](https://slack.aimstack.io/) so we can debug this more interactively?

**Comment by alberttorosyan** [comment]
Hi @dallmann-uniwue! Thanks for your input; this might help us to finally find the root cause of the issue.
Would you mind to share some minimal example where the above mentioned setting fixes the problem? That would be a huge help 🙏 
Also we would like to reproduce with the exact same environment as you have, so having package versions will be helpful as well.

**Comment by dallmann-uniwue** [comment]
Hi @alberttorosyan,
I'm not sure when I will find the time to design a minimal working example for this issue, but I can supply some specifics about the environment right away:

OS: Fedora 35
Python: 3.9.9 (managed by PyEnv)
```
torch==1.9.1
pytorch-lightning==1.4.7
aim==3.6.3
```
I hope this already helps. If you need any more specifics, please let me know.

**Comment by devfox-se** [comment]
Hi @dallmann-uniwue @mikel-brostrom 

We would like to go forward with this yet we still cannot reproduce nor understand wheres the issue.
So for that I would ask you to set gRPC environment variable to log every step it goes trough. We then might be able to track down the issue on our end.

`export GRPC_TRACE=all`

Will wait for your logs,
Thanks!

**Comment by dallmann-uniwue** [comment]
Hi,
I will hopefully find some time tonight to give it a try!

**Comment by dallmann-uniwue** [comment]
Hi,
I ran my code without the above fix with the mentioned environment variable set. Unfortunately, it does not output any more infos than before (I've pruned my own logs from the output):
[grpc-output.txt](https://github.com/aimhubio/aim/files/8336298/grpc-output.txt)

I noticed that I was not able to consistently reproduce the issue. Today, it failed one out of three times with the above message. I also tried to set `export GRPC_VERBOSITY=INFO` which resulted in large amounts of logging data. 
[grpc-output-debug.zip](https://github.com/aimhubio/aim/files/8336433/grpc-output-debug.zip)

I could'nt make sense of the output, but I hope this helps.

**Comment by dallmann-uniwue** [comment]
Hi,
did you have time to take a look at the logs and could you identify the issue?

**Comment by devfox-se** [comment]
@dallmann-uniwue sorry for late response - we have been checking lots of stuff to reproduce this
What we have tried so far:
- Simulate package loss / high ping on remote server
- Experiment with  `keepalive` gRPC properties 
- Run processes in `fork` <- we believe this can be an issue really but still couldnt reproduce it yet

We came across this gRPC guide - https://github.com/grpc/grpc/blob/master/doc/fork_support.md
Apparently users can face issue when using gRPC resources in forked process, it's worth the try to set the env variables and see wether or not the issue has gone. Would appreciate your feedback on this.

```
export GRPC_ENABLE_FORK_SUPPORT=true
export GRPC_POLL_STRATEGY=poll
```

Beside this we would appreciate any sample testcase that is failing for you for our further investigation. Thanks!

**Comment by dallmann-uniwue** [comment]
@devfox-se thank you for still investigating this issue! 
I've tried the environment variables you suggested with `fork` enabled and can report that it fixes this issue in my case. 

However, there seems to be a drawback. The training gets stuck when spinning up the DataLoader workers if the parallelization is set to  `num_workers > 6`. Below that I did not encounter any issues. I tried `num_workers = 0, 1, 2, 4, 6, 8`.

**Comment by lminer** [comment]
i'm having the same issue

**Comment by vikigenius** [comment]
I am also facing the same issue as @lminer when using the suggested environment variables.

**Comment by alberttorosyan** [comment]
@mikel-brostrom, With the Aim 3.19 we've completely changed the tracking server implementation. It it not using gRPC anymore.
Could you please try it out and see if the new tracking server works fine in this case?
