### ISSUE TITLE
SQLite issue when running many jobs in parallel

### ISSUE THREAD

**Issue by devfox-se** [aimhubio/aim#1299]
## 🐛 Bug

When many jobs are launched at exactly the same time it seems there is an issue with sql database access.

### To reproduce

Use slurm to launch ~50 jobs

### Additional context

```Traceback (most recent call last):
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: unable to open database file
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/tthonet/src/RL4REC/pretrain_ranker.py", line 77, in <module>
    aim_logger.log_hyperparams(logger_arg_dict)
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/pytorch_lightning/utilities/distributed.py", line 50, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/aim/sdk/adapters/pytorch_lightning.py", line 74, in log_hyperparams
    hparams = self.experiment.meta_run_attrs_tree.subtree('hparams')
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/pytorch_lightning/loggers/base.py", line 43, in experiment
    return get_experiment() or DummyExperiment()
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/pytorch_lightning/utilities/distributed.py", line 50, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/pytorch_lightning/loggers/base.py", line 41, in get_experiment
    return fn(self)
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/aim/sdk/adapters/pytorch_lightning.py", line 53, in experiment
    self._run = Run(
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/aim/sdk/run.py", line 298, in __init__
    self.props
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/aim/sdk/run.py", line 479, in props
    self._init_props()
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/aim/sdk/run.py", line 493, in _init_props
    self._props.experiment = 'default'
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/aim/storage/structured/sql_engine/entities.py", line 116, in experiment
    session.flush()
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3363, in flush
    self._flush(objects)
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3463, in _flush
    flush_context.execute()
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    _emit_update_statements(
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1000, in _emit_update_statements
    c = connection._execute_20(
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/home/tthonet/src/RL4REC/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
[SQL: UPDATE run SET updated_at=?, experiment_id=? WHERE run.id = ?]
[parameters: ('2022-01-28 17:17:37.399610', 1, 46)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Comment by devfox-se** [comment]
The only error I currently observe related to `SQLite` is when the aim repo is not inited and and many processes try to write in `Run` table when its not created yet.

Other thank that when the DB exists, all the processes are managing to write data in the `run` table but other than that I observe Resource LOCK issue on rocksdb side

```Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/arthur/projects/aim/aim/ext/cleanup/__init__.py", line 80, in _cleanup
    finalizer()
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/weakref.py", line 591, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/Users/arthur/projects/aim/aim/sdk/run.py", line 102, in _close
    self.finalize_run()
  File "/Users/arthur/projects/aim/aim/sdk/run.py", line 80, in finalize_run
    index = self.repo._get_index_tree('meta', timeout=timeout).view(b'')
  File "/Users/arthur/projects/aim/aim/sdk/repo.py", line 265, in _get_index_tree
    return self._get_index_container(name, timeout).tree()
  File "/Users/arthur/projects/aim/aim/sdk/repo.py", line 278, in _get_index_container
    container = RocksContainer(path, read_only=False, timeout=timeout)
  File "/Users/arthur/projects/aim/aim/storage/rockscontainer.py", line 103, in __init__
    self.writable_db
  File "/Users/arthur/projects/aim/aim/storage/rockscontainer.py", line 147, in writable_db
    db = self.db
  File "/Users/arthur/projects/aim/aim/storage/rockscontainer.py", line 139, in db
    self._db = aimrocks.DB(str(self.path),
  File "src/aimrocks/_rocksdb.pyx", line 1671, in aimrocks._rocksdb.DB.__cinit__
  File "src/aimrocks/_rocksdb.pyx", line 88, in aimrocks._rocksdb.check_status
aimrocks.errors.RocksIOError: b'IO error: While lock file: /Users/arthur/projects/aim/workspace/.aim/meta/index/LOCK: Resource temporarily unavailable'
(aim) ➜  workspace git:(main) ✗ 
```
