### ISSUE TITLE
Pytorch-Lightning logger in Lightning-Flash: TypeError: finalize() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by andife** [aimhubio/aim#1794]
## 🐛 Bug

I wanted to use aim for logging the process of the following task: 
https://lightning-flash.readthedocs.io/en/stable/reference/semantic_segmentation.html

flash is built up of pytorch-lightning

```
The message I get is:

05/24/2022 23:26:12 - INFO - torch.distributed.nn.jit.instantiator -   Created a temporary directory at /tmp/tmpv3xvz5pn
05/24/2022 23:26:12 - INFO - torch.distributed.nn.jit.instantiator -   Writing /tmp/tmpv3xvz5pn/_remote_module_non_sriptable.py
/home/andreas/conda/envs/flash/lib/python3.9/site-packages/pytorch_lightning/utilities/parsing.py:261: UserWarning: Attribute 'metrics' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['metrics'])`.
  rank_zero_warn(
Using 'mobilenetv3_large_100' provided by qubvel/segmentation_models.pytorch (https://github.com/qubvel/segmentation_models.pytorch).
Using 'fpn' provided by qubvel/segmentation_models.pytorch (https://github.com/qubvel/segmentation_models.pytorch).
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]

  | Name          | Type               | Params
-----------------------------------------------------
0 | train_metrics | ModuleDict         | 0
1 | val_metrics   | ModuleDict         | 0
2 | test_metrics  | ModuleDict         | 0
3 | head          | FPN                | 4.9 M
4 | backbone      | MobileNetV3Encoder | 3.0 M
-----------------------------------------------------
1.9 M     Trainable params
2.9 M     Non-trainable params
4.9 M     Total params
19.561    Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]/home/andreas/conda/envs/flash/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:240: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 32 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/home/andreas/conda/envs/flash/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:240: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 32 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Epoch 2: 100%|█| 250/250 [01:01<00:00,  4.03it/s, loss=0.174, v_num=564a, train_jaccardindex_step=0.359, train_cross_entropy_step=0.173, val_jaccardindex=0.373, val_c
Traceback (most recent call last):
  File "/mnt/data/WorkDirAndreas/flash_example.py", line 42, in <module>
    trainer.finetune(model, datamodule=datamodule, strategy="freeze")
  File "/home/andreas/anaconda3/envs/flash/lib/python3.9/site-packages/flash/core/trainer.py", line 164, in finetune
    return super().fit(model, train_dataloader, val_dataloaders, datamodule)
  File "/home/andreas/conda/envs/flash/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit
    self._call_and_handle_interrupt(
  File "/home/andreas/conda/envs/flash/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/andreas/conda/envs/flash/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/andreas/conda/envs/flash/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1248, in _run
    self._call_teardown_hook()
  File "/home/andreas/conda/envs/flash/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1529, in _call_teardown_hook
    logger.finalize("success")
  File "/home/andreas/conda/envs/flash/lib/python3.9/site-packages/pytorch_lightning/utilities/rank_zero.py", line 32, in wrapped_fn
    return fn(*args, **kwargs)
TypeError: finalize() takes 1 positional argument but 2 were given

```

### To reproduce

Added pytorch-lightning logger of aim to flash example: 

```

import torch

import flash
from flash.core.data.utils import download_data
from flash.image import SemanticSegmentation, SemanticSegmentationData
from aim.pytorch_lightning import AimLogger


# 1. Create the DataModule
# The data was generated with the  CARLA self-driving simulator as part of the Kaggle Lyft Udacity Challenge.
# More info here: https://www.kaggle.com/kumaresanmanickavelu/lyft-udacity-challenge
download_data(
    "https://github.com/ongchinkiat/LyftPerceptionChallenge/releases/download/v0.1/carla-capture-20180513A.zip",
    "./data",
)

# track experimental data by using Aim
aim_logger = AimLogger(
    experiment='aim_on_pt_lightning',
    train_metric_prefix='train_',
    val_metric_prefix='val_',
)

datamodule = SemanticSegmentationData.from_folders(
    train_folder="data/CameraRGB",
    train_target_folder="data/CameraSeg",
    val_split=0.1,
    transform_kwargs=dict(image_size=(256, 256)),
    num_classes=21,
    batch_size=4,
)

# 2. Build the task
model = SemanticSegmentation(
    backbone="mobilenetv3_large_100",
    head="fpn",
    num_classes=datamodule.num_classes,
)

# 3. Create the trainer and finetune the model
trainer = flash.Trainer(max_epochs=3, gpus=[0], logger=aim_logger)
trainer.finetune(model, datamodule=datamodule, strategy="freeze")

# 4. Segment a few images!
datamodule = SemanticSegmentationData.from_files(
    predict_files=[
        "data/CameraRGB/F61-1.png",
        "data/CameraRGB/F62-1.png",
        "data/CameraRGB/F63-1.png",
    ],
    batch_size=3,
)
predictions = trainer.predict(model, datamodule=datamodule)
print(predictions)

# 5. Save the model!
trainer.save_checkpoint("semantic_segmentation_model.pt")

```

### Expected behavior

Log the process

### Environment

- Aim Version (e.g., 3.0.1)
- Python version
- pip version
- OS (e.g., Linux)
- Any other relevant information

**Comment by mihran113** [comment]
hey @andife! Thanks a lot for the report, I'll have a look into it and get back to you with further updates.

**Comment by gorarakelyan** [comment]
closing this issue as it was resolved. @andife pls feel free to reopen it if issue will occur again.
