### ISSUE TITLE
Grpc Error: Exception calling application: 0.1 has type float, but expected one of: bytes, unicode

### ISSUE THREAD

**Issue by Natlem** [aimhubio/aim#1833]
## 🐛 Bug

Bug happens when Run object is contained inside a wrapper while using num_workers=0 with pytorch Dataloader.
This didn't happen on aim version 3.8.3. 
This bug also only seems to happens when using aim with remote server

### To reproduce

```
import torch
import torchvision
from aim import Run


class ExpTracker:
    def __init__(self, aim_run=None, console_print: bool = False):
        self.aim_run = aim_run
        self.console_print = console_print
        self.hparams = {}

    def track(self, name: str, step: int, context: dict, value):
        if self.console_print:
            print('{} {} at {} in {}'.format(name, value, step, context['subset']))
        if self.aim_run is not None and not isinstance(self.aim_run, dict):
            self.aim_run.track(value, name=name, step=step, context=context)

    def set_aim(self, aim):
        self.aim_run = aim

    def set_config(self, config: dict):
        if self.aim_run is not None:
            self.aim_run["hparams"] = config
        self.hparams = config

    def get_config(self) -> dict:
        return self.hparams


if __name__ == "__main__":
    run = Run(
        repo='aim://IP_ADDR',
        experiment='Sagemaker training whatever'
    )

    exp = ExpTracker(console_print=True)
    exp.set_aim(run)
    exp.set_config({
        'model': "args.model_name",
        "learning_rate": 0.1,
        "batch_size": 1,
        "num_train_epochs": 10,
    })

    train_loader = torch.utils.data.DataLoader(
        torchvision.datasets.MNIST('/tmp/', train=True, download=True,
                                   transform=torchvision.transforms.Compose([
                                       torchvision.transforms.ToTensor(),
                                       torchvision.transforms.Normalize(
                                           (0.1307,), (0.3081,))
                                   ])),
        batch_size=2, shuffle=True)

    test_loader = torch.utils.data.DataLoader(
        torchvision.datasets.MNIST('/tmp/', train=False, download=True,
                                   transform=torchvision.transforms.Compose([
                                       torchvision.transforms.ToTensor(),
                                       torchvision.transforms.Normalize(
                                           (0.1307,), (0.3081,))
                                   ])),
        batch_size=1, shuffle=True)

    for i, e in enumerate(train_loader):
        exp.track(name="test", step=i, context={"subset": "train"}, value=i)
        break

```

Process stop and hang on:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/user/anaconda2/envs/spacy/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/user/anaconda2/envs/spacy/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/anaconda2/envs/spacy/lib/python3.9/site-packages/aim/ext/transport/rpc_queue.py", line 48, in worker
    if self._try_exec_task(task_f, *args):
  File "/home/user//anaconda2/envs/spacy/lib/python3.9/site-packages/aim/ext/transport/rpc_queue.py", line 69, in _try_exec_task
    raise e
  File "/home/user/anaconda2/envs/spacy/lib/python3.9/site-packages/aim/ext/transport/rpc_queue.py", line 65, in _try_exec_task
    task_f(*args)
  File "/home/user/anaconda2/envs/spacy/lib/python3.9/site-packages/aim/ext/transport/client.py", line 129, in _run_write_instructions
    response = self.remote.run_write_instructions(message_stream_generator())
  File "/home/user/anaconda2/envs/spacy/lib/python3.9/site-packages/grpc/_channel.py", line 1131, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/user/anaconda2/envs/spacy/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 0.1 has type float, but expected one of: bytes, unicode"
	debug_error_string = "{"created":"@1654178657.569362298","description":"Error received from peer ipv4:176.31.254.159:9999","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"Exception calling application: 0.1 has type float, but expected one of: bytes, unicode","grpc_status":2}"
>
```

### Environment

- Aim Version: 3.10.3

**Comment by Natlem** [comment]
Hi @mihran113,

I did this check (as shown in screenshot)
![image](https://user-images.githubusercontent.com/4445315/172376597-eda4ad07-087d-4805-9ffb-3315104bff2d.png)

The problem is still here. Maybe I did this wrong ?

**Comment by mihran113** [comment]
Hi @Natlem, from the screenshot above I understand that you restarted the ui server only, can I ask you to restart the tracking server as well with the newest version and check again? (the `aim server` command)

**Comment by Natlem** [comment]
@mihran113, tested with re-run the server command as well. It worked perfectly now.

Thanks !!!

**Comment by mihran113** [comment]
@Natlem glad that helped 🙌
