### ISSUE TITLE
aimrocks RocksIOError on NFS share

### ISSUE THREAD

**Issue by pkubik** [aimhubio/aim#1865]
## 🐛 Bug

I initialized a directory with `aim init` on my NFS share, and run several jobs pointing to this directory.
Initially all metrics and params were logged properly, but after a while logging stopped and it seems like it started to repeatedly fail from the logs.

```
aimrocks.errors.RocksIOError: b'IO error: While appending to file: /nas/projects/auto-ml/models/pkubik/pc/.aim/meta/chunks/07a1749cee044a69a80226d82f0d0b0c/000027.log: Input/output error'
Traceback (most recent call last):
  File "src/aimrocks/lib_rocksdb.pyx", line 89, in aimrocks.lib_rocksdb.check_status
aimrocks.errors.RocksIOError: b'IO error: While appending to file: /nas/projects/auto-ml/models/pkubik/pc/.aim/meta/chunks/07a1749cee044a69a80226d82f0d0b0c/000027.log: Input/output error'
Exception ignored in: 'aimrocks.lib_rocksdb.DB.write'
Traceback (most recent call last):
  File "src/aimrocks/lib_rocksdb.pyx", line 89, in aimrocks.lib_rocksdb.check_status
aimrocks.errors.RocksIOError: b'IO error: While appending to file: /nas/projects/auto-ml/models/pkubik/pc/.aim/meta/chunks/07a1749cee044a69a80226d82f0d0b0c/000027.log: Input/output error'
Traceback (most recent call last):
  File "src/aimrocks/lib_rocksdb.pyx", line 89, in aimrocks.lib_rocksdb.check_status
aimrocks.errors.RocksIOError: b'IO error: Stale file handle'
Exception ignored in: 'aimrocks.lib_rocksdb.DB.write'
Traceback (most recent call last):
  File "src/aimrocks/lib_rocksdb.pyx", line 89, in aimrocks.lib_rocksdb.check_status
aimrocks.errors.RocksIOError: b'IO error: Stale file handle'
Traceback (most recent call last):
  File "src/aimrocks/lib_rocksdb.pyx", line 89, in aimrocks.lib_rocksdb.check_status
aimrocks.errors.RocksIOError: b'IO error: Stale file handle'
Exception ignored in: 'aimrocks.lib_rocksdb.DB.write'
Traceback (most recent call last):
  File "src/aimrocks/lib_rocksdb.pyx", line 89, in aimrocks.lib_rocksdb.check_status
aimrocks.errors.RocksIOError: b'IO error: Stale file handle'
Traceback (most recent call last):
  File "src/aimrocks/lib_rocksdb.pyx", line 89, in aimrocks.lib_rocksdb.check_status
aimrocks.errors.RocksIOError: b'IO error: Stale file handle'
Exception ignored in: 'aimrocks.lib_rocksdb.DB.write'
Traceback (most recent call last):
  File "src/aimrocks/lib_rocksdb.pyx", line 89, in aimrocks.lib_rocksdb.check_status
aimrocks.errors.RocksIOError: b'IO error: Stale file handle'
```
(this repeats several time, I guess on each logging attempt)

After manual inspection the mentioned file doesn't seem to exist anymore. There is a similar log file with a higher number in given directory - in this case `000039.log`, and a bunch of other files:
```
000024.sst  000026.sst  000028.sst  000032.sst  000038.sst  000039.log  000040.sst  CURRENT  IDENTITY  LOCK  LOG  LOG.old.1654955991303666  MANIFEST-000033  OPTIONS-000007  OPTIONS-000036
```

### To reproduce

Setup training job with:
```
aim_run = aim.Run(
    run_hash=name,
    repo=os.environ.get("AIM_ROOT_DIR"), # shared NFS directory for multiple jobs
    experiment=experiment_name,
)
```

Proceed with training, logging a set of metrics one every minute.

### Expected behavior

Metrics are logged continuously.

### Environment

- Aim v3.10.3
- Python 3.8.12
- pip 21.2.4
- Ubuntu 20.04 from NVidia NVCR docker image nvcr.io/nvidia/pytorch:22.03-py3
- On Kubernetes cluster

**Comment by alberttorosyan** [comment]
@mahnerak have you seen such error previously? as I recall you had a setup for NFS with Aim?

**Comment by pkubik** [comment]
After I restarted the jobs they seem to log correctly without errors.

**Comment by mahnerak** [comment]
I’ve seen stale handle errors a lot in my NFS setup (in cases not involving aim at all).
I guess it’s mainly an NFS issue, but I’ll look into it.

Please let me know if such NFS-specific issues happen in future.

**Comment by pkubik** [comment]
Is it in general safer to run a single aim server on the cluster and attach my jobs by TCP?

**Comment by pkubik** [comment]
I wouldn't necessarily focus on the stale handle errors that much. The most important part seems to be that a process is trying to append to a log file that no longer exist. Each job is likely only accessing their own files, and UI is most likely not changing any files.

I guess it could occur due to multi-processing that occur in Pytorch.
There might be also some inconsistency in NFS as it's quite old and crazy. Could it be that the error occurs due to some caching mechanism?

Is this file structure I pasted at the top of the issue specific to aim or rocksdb?

**Comment by alberttorosyan** [comment]
@pkubik wrt this:
> Is it in general safer to run a single aim server on the cluster and attach my jobs by TCP?

`aim server` is used for remote tracking by several users. It works reasonably well, but it is still considered as an experimental feature. We are planning to fix the known issues and make a stable release in the next milestone. Some things to be aware if you're trying to use it now:
- With many parallel trainings remote tracking will slow down if the write frequency is too high (i.e. writing many metrics every second)

As for your second question, the .log and .sst files are internal for `rocksdb`. .log is a write ahead log which gets flushed based on the options used. In general, the situation with missing .log file should not occur since it is managed by a single process, but this might be a bug on `rocksdb` side. We have to dig further into this issue to know for sure.
