### ISSUE TITLE
ModuleNotFoundError: No module named 'aim.stack_grps'

### ISSUE THREAD

**Issue by jguhlin** [aimhubio/aim#224]
Trying to get aim up and running. From the user account it reports docker not installed (not true, but I'm assuming it requires root). Fresh conda install as root, conda create -n keras python=3.8 pip 

then pip install aim
aim up
```Traceback (most recent call last):
  File "/root/anaconda3/envs/keras/bin/aim", line 5, in <module>
    from aim.commands.cli import cli
  File "/root/anaconda3/envs/keras/lib/python3.8/site-packages/aim/commands/cli.py", line 3, in <module>
    from aim.commands.cmd_provision import provision_command
  File "/root/anaconda3/envs/keras/lib/python3.8/site-packages/aim/commands/cmd_provision.py", line 4, in <module>
    from aim.commands.helpers import controller_args, aim_home_option, init_aim_home_option, pass_aim_context, \
  File "/root/anaconda3/envs/keras/lib/python3.8/site-packages/aim/commands/helpers.py", line 4, in <module>
    from aim.config.aim_context import AimContext, AccountContext
  File "/root/anaconda3/envs/keras/lib/python3.8/site-packages/aim/config/aim_context.py", line 3, in <module>
    import aim.controllers
  File "/root/anaconda3/envs/keras/lib/python3.8/site-packages/aim/controllers/__init__.py", line 1, in <module>
    from aim.controllers.ctl_network_environment import NetEnvController
  File "/root/anaconda3/envs/keras/lib/python3.8/site-packages/aim/controllers/ctl_network_environment.py", line 10, in <module>
    from aim.stack_grps.grp_application import ApplicationStackGroup
ModuleNotFoundError: No module named 'aim.stack_grps'```

Any ideas?

**Comment by gorarakelyan** [comment]
Please run `pip3 install aim-cli` to install `aim`. Package name in pypi is `aim-cli`.

**Comment by jguhlin** [comment]
Ah, damnit. I had it right in one conda env but not the other. Sorry!
