### ISSUE TITLE
Bug in run view. Type error.

### ISSUE THREAD

**Issue by GeorgePearse** [aimhubio/aim#2240]
## 🐛 Bug

![image](https://user-images.githubusercontent.com/47161914/193861345-f1ab324f-bead-43ff-91d0-c4c202a0e5f9.png)

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 405, in run_asgi
    self.scope, self.receive, self.send
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/starlette/routing.py", line 390, in handle
    await self.app(scope, receive, send)
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/starlette/middleware/gzip.py", line 18, in __call__
    await responder(scope, receive, send)
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/starlette/middleware/gzip.py", line 35, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/fastapi/routing.py", line 220, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/fastapi/routing.py", line 152, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/aim/web/api/runs/views.py", line 143, in run_params_api
    return JSONResponse(response)
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/starlette/responses.py", line 53, in __init__
    self.body = self.render(content)
  File "/home/georgepearse/environments/vision-research/lib/python3.7/site-packages/starlette/responses.py", line 166, in render
    separators=(",", ":"),
  File "/opt/conda/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/opt/conda/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/conda/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/conda/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
INFO:root:wetag_C&DPB003
```

### To reproduce

Using with pytorch-lightning. Logging things like &s in class material names (I log the class label list to my experiment tracker)

### Expected behavior

No bug 

### Environment

```
absl-py==1.2.0
aim==3.13.4
aim-ui==3.13.4
aimrecords==0.0.7
aimrocks==0.2.1
aiofiles==22.1.0
aiohttp==3.8.3
aiosignal==1.2.0
alembic==1.8.1
antlr4-python3-runtime==4.9.3
anyio==3.6.1
argcomplete==2.0.0
async-timeout==4.0.2
asynctest==0.13.0
attrs==22.1.0
autopage==0.5.1
backcall==0.2.0
backports.cached-property==1.0.2
backports.zoneinfo==0.2.1
base58==2.0.1
-e git+ssh://git@github.com/BinItAI/vision-research.git@5b54252a5c48ec2415c13ebd14768f8c4c64376d#egg=binit_vision_utils&subdirectory=utils
boto3==1.24.84
botocore==1.27.84
cachetools==5.2.0
certifi==2022.9.24
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
cliff==3.10.1
cmaes==0.8.2
cmd2==2.4.2
colorlog==6.7.0
commonmark==0.9.1
cryptography==38.0.1
cycler==0.11.0
dacite==1.6.0
debugpy==1.6.3
decorator==5.1.1
Deprecated==1.2.13
dill==0.3.5.1
dnspython==2.2.1
docker-pycreds==0.4.0
entrypoints==0.4
eventlet==0.33.1
fastapi==0.67.0
fiftyone==0.16.6
fiftyone-brain==0.9.1
fiftyone-db==0.3.0
filelock==3.8.0
fonttools==4.37.4
frozenlist==1.3.1
fsspec==2022.8.2
future==0.18.2
gcsfs==2022.8.2
gitdb==4.0.9
GitPython==3.1.27
glob2==0.7
google-api-core==2.10.1
google-auth==2.12.0
google-auth-oauthlib==0.4.6
google-cloud-bigquery==3.3.3
google-cloud-bigquery-storage==2.16.1
google-cloud-core==2.3.2
google-cloud-storage==2.5.0
google-crc32c==1.5.0
google-resumable-media==2.4.0
googleapis-common-protos==1.56.4
graphql-core==3.1.7
greenlet==1.1.3
grpcio==1.49.1
grpcio-status==1.48.2
h11==0.12.0
h2==4.1.0
hpack==4.0.0
httpcore==0.15.0
httpx==0.23.0
hydra-core==1.2.0
hypercorn==0.14.3
hyperframe==6.0.1
idna==3.4
imageio==2.22.0
importlib-metadata==4.13.0
importlib-resources==5.9.0
ipykernel==6.16.0
ipython==7.34.0
ipywidgets==8.0.0
jedi==0.18.1
Jinja2==3.1.2
jmespath==1.0.1
joblib==1.2.0
jupyter-core==4.11.1
jupyter_client==7.3.5
jupyterlab-widgets==3.0.3
kaleido==0.2.1
kiwisolver==1.4.4
lightning-bolts==0.5.0
Mako==1.2.3
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.5.3
matplotlib-inline==0.1.6
mongoengine==0.20.0
motor==2.5.1
multidict==6.0.2
ndjson==0.3.1
nest-asyncio==1.5.6
networkx==2.6.3
numpy==1.21.6
oauthlib==3.2.1
omegaconf==2.2.3
opencv-python-headless==4.6.0.66
optuna==2.10.1
packaging==21.3
pandas==1.3.5
parso==0.8.3
pathtools==0.1.2
patool==1.12
pbr==5.10.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.2.0
plotly==4.14.3
pprintpp==0.4.0
prettytable==3.4.1
priority==2.0.0
promise==2.3
prompt-toolkit==3.0.31
proto-plus==1.22.1
protobuf==3.20.2
psutil==5.9.2
ptyprocess==0.7.0
py3nvml==0.2.7
pyarrow==9.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pydantic==1.10.2
pyDeprecate==0.3.2
Pygments==2.13.0
pymongo==3.12.3
pyparsing==3.0.9
pyperclip==1.8.2
python-dateutil==2.8.2
python-dotenv==0.21.0
python-multipart==0.0.5
pytorch-lightning==1.6.5
pytz==2022.4
pytz-deprecation-shim==0.1.0.post0
PyWavelets==1.3.0
PyYAML==6.0
pyzmq==24.0.1
requests==2.28.1
requests-oauthlib==1.3.1
RestrictedPython==5.2
retrying==1.3.3
rfc3986==1.5.0
rich==12.5.1
rsa==4.9
s3transfer==0.6.0
scaleapi==2.9.0
scikit-image==0.19.3
scikit-learn==1.0.2
scipy==1.7.3
sentinel==0.3.0
sentry-sdk==1.9.9
setproctitle==1.3.2
shortuuid==1.0.9
six==1.16.0
smmap==5.0.0
sniffio==1.3.0
sortedcontainers==2.4.0
SQLAlchemy==1.4.41
sse-starlette==0.10.3
sseclient-py==1.7.2
starlette==0.16.0
stevedore==3.5.0
strawberry-graphql==0.96.0
tabulate==0.8.10
tensorboard==2.10.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
threadpoolctl==3.1.0
tifffile==2021.11.2
toml==0.10.2
torch==1.12.0
torchmetrics @ git+https://github.com/raghavmecheri/lightning-metrics@7a9ffed228f4052ea971a9e4f39d8ca7828298b9
torchvision==0.13.0
tornado==6.2
tqdm==4.64.1
traitlets==5.4.0
typing_extensions==4.3.0
tzdata==2022.4
tzlocal==4.2
universal-analytics-python3==1.1.1
urllib3==1.26.12
uvicorn==0.18.3
voxel51-eta==0.8.1
wandb==0.13.1
wcwidth==0.2.5
Werkzeug==2.2.2
widgetsnbextension==4.0.3
wrapt==1.14.1
wsproto==1.2.0
xmltodict==0.13.0
yarl==1.8.1
zipp==3.8.1
```

**Comment by gorarakelyan** [comment]
Closing the issue as the fix has been shipped and confirmed!
