### ISSUE TITLE
Runs hanging "in progress" & can't `aim runs close` due to IO Error: While lock file

### ISSUE THREAD

**Issue by mohammed-zia** [aimhubio/aim#2436]
## 🐛 Bug

Most recent run in Aim always hangs "In progress" until another run is started. When trying to force close the run using `aim runs close e23474f7c433427ab61ec693` I get the stack trace:

```
Closing runs:   0%|                                                                                                                                                               | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/tf/bin/aim", line 8, in <module>
    sys.exit(cli_entry_point())
  File "/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/aim/cli/runs/commands.py", line 179, in close_runs
    for _ in tqdm.tqdm(
  File "/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/user/miniconda3/envs/tf/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
  File "/home/user/miniconda3/envs/tf/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/aim/cli/runs/commands.py", line 175, in close_run
    index_manager.index(run_hash)
  File "/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/aim/sdk/index_manager.py", line 116, in index
    meta_tree = self.repo.request_tree('meta', run_hash, read_only=False).subtree('meta')
  File "/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/aim/sdk/repo.py", line 313, in request_tree
    return self.request(name, sub, read_only=read_only, from_union=from_union).tree()
  File "/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/aim/sdk/repo.py", line 339, in request
    container = self._get_container(path, read_only=False, from_union=False)
  File "/home/user/miniconda3/envs/tf/lib/python3.9/site-packages/aim/sdk/repo.py", line 279, in _get_container
    container = RocksContainer(path, read_only=read_only)
  File "aim/storage/rockscontainer.pyx", line 104, in aim.storage.rockscontainer.RocksContainer.__init__
  File "aim/storage/rockscontainer.pyx", line 154, in aim.storage.rockscontainer.RocksContainer.writable_db
  File "aim/storage/rockscontainer.pyx", line 146, in aim.storage.rockscontainer.RocksContainer.db
  File "src/aimrocks/lib_rocksdb.pyx", line 1686, in aimrocks.lib_rocksdb.DB.__cinit__
  File "src/aimrocks/lib_rocksdb.pyx", line 89, in aimrocks.lib_rocksdb.check_status
aimrocks.errors.RocksIOError: b'IO error: While lock file: /home/user/Desktop/classification/.aim/meta/chunks/e23474f7c433427ab61ec693/LOCK: Resource temporarily unavailable'
```

I see there's another #2434 with a similar problem maybe, so feel free to delete if this is considered duplicate although unlike the other issue I am not using remote server and the error only appears once when trying to close the run manually. 

Exiting the local server from terminal and restarting with `aim up` doesn't change it.

### To reproduce

I am using `aim.tensorflow.AimCallback` to interact with the run metadata. 

```
from aim.tensorflow import AimCallback

config = model.get_config()['layers']

a = {}
for i in config:
  a.setdefault(i['class_name'], []).append(i['config'])

aim_callback = AimCallback(experiment="aim_on_keras")

for key, val in a.items():
  aim_callback._run[key] = val

aim_callback._run['data_train_tensor'] = X_train.shape
aim_callback._run['data_test_tensor'] = X_test.shape
aim_callback._run['label_train_tensor'] = Y_train.shape
aim_callback._run['label_test_tensor'] = Y_test.shape
aim_callback._run['epochs'] = epochs
aim_callback._run['batch_size'] = batch_size
aim_callback._run['max_words'] = MAX_NB_WORDS
aim_callback._run['max_seq_length'] = MAX_SEQUENCE_LENGTH
aim_callback._run['test_size'] = TEST_SIZE
```

and using `callbacks=[aim_callback]` in keras `model.fit()`

### Expected behavior

Run should automatically end after notebook completes execution.

Run should also close when manually using `aim runs close xxxx`

### Environment

- Aim Version (e.g., 3.0.1)
aim==3.15.1
aim-ui==3.15.1
aimrecords==0.0.7
aimrocks==0.2.1
- Python version
Python 3.9.15
- pip version
pip 22.3.1
- OS (e.g., Linux)
Ubuntu 20.04.1
- Any other relevant information

**Comment by mohammed-zia** [comment]
Running `find .aim -name "17db37c8b6f74fe3baf98de2*"` during active run:

```
.aim/meta/progress/17db37c8b6f74fe3baf98de2
.aim/meta/chunks/17db37c8b6f74fe3baf98de2
.aim/check_ins/17db37c8b6f74fe3baf98de2-0000000000000014-progress-1671207652.77-00026
.aim/check_ins/17db37c8b6f74fe3baf98de2-0000000000000001-starting-1671207587.74-00000
.aim/locks/17db37c8b6f74fe3baf98de2.softlock
.aim/seqs/progress/17db37c8b6f74fe3baf98de2
.aim/seqs/chunks/17db37c8b6f74fe3baf98de2
```

and remains the same output after the run "completes" but doesn't actually complete. 

But when I kick off another run, that changes to:

```
.aim/meta/progress/17db37c8b6f74fe3baf98de2
.aim/meta/chunks/17db37c8b6f74fe3baf98de2
.aim/check_ins/17db37c8b6f74fe3baf98de2-0000000000000111-progress-1671208128.40-00001
.aim/check_ins/17db37c8b6f74fe3baf98de2-0000000000000001-starting-1671207587.74-00000
.aim/seqs/progress/17db37c8b6f74fe3baf98de2
.aim/seqs/chunks/17db37c8b6f74fe3baf98de2
```

**Comment by mohammed-zia** [comment]
Closing this issue - I completely missed that I need `run.finalize()` in a notebook - when running as script it works as expected. Sorry for false alarm!
