### ISSUE TITLE
SDK `query_runs` fails with `TypeError`

### ISSUE THREAD

**Issue by inc0** [aimhubio/aim#2457]
## 🐛 Bug

While trying to run `repo.query_runs(query)`, followed by turning iterator into actual values, method fails with following traceback:

```
Traceback (most recent call last):
  File "temp.py", line 12, in <module>
    list(runs)
  File "/home/inc0/aim/aim/sdk/sequence_collection.py", line 235, in iter
    yield from run_seq
  File "/home/inc0/aim/aim/sdk/sequence_collection.py", line 122, in iter
    match = self.query.check(**{'run': run_view, seq_var: seq_view})
TypeError: check() keywords must be strings
```

### To reproduce
```
repo = Repo(repo_url)
runs = repo.query_runs(f"run.creation_time > {start_timestamp}")
list(runs)
```

### Expected behavior

Not throwing error

### Environment

- Aim Version - 3.15.2
- Python version - 3.8.15

### Additional context

After a bit of debugging I think issue is that [QueryRunSequenceCollection](https://github.com/aimhubio/aim/blob/main/aim/sdk/sequence_collection.py#L194) doesn't have `sequence_name` method. After I added this method, next error was about missing `allowed_dtypes`. This one is a bit harder as return type of this sequence is complex (`Run` objects, I think). I'm not sure what's best dtype to fill there.

**Comment by mihran113** [comment]
Hey @inc0, thanks for reaching out, the query SDK is a little bit counter intuitive currently and is on our roadmap to change :) 
your desired result can be achieved via this code block: 
```
repo = Repo(repo_url)
query_res = repo.query_runs(f"run.creation_time > {start_timestamp}").iter_runs()
runs = [item.run for item in query_res]
```

**Comment by inc0** [comment]
thanks @mihran113! That works. I've also published PR that seems to be fixing this issue, should we want to avoid it in the future.
