### ISSUE TITLE
Race condition when creating aim runs

### ISSUE THREAD

**Issue by n-gao** [aimhubio/aim#2489]
## 🐛 Bug

There seems to be a race condition if multiple jobs try to write to the same repository.

### To reproduce
Start multiple slurm jobs with the same new `experiment` value.

### Expected behavior

All of them should survive.
A current workaround is something like this:
```python
def _try_create_aim_run(repo, experiment, ntries=5):
    try:
        return aim.Run(repo=repo, experiment=experiment)
    except Exception as e:
        if ntries > 0:
            time.sleep(1.0)
            return _try_create_aim_run(repo, experiment, ntries - 1)
        raise e
```

### Environment

- Aim Version 3.5.12
- Python version 3.8

### Additional context

```
Traceback (most recent call last):

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)

sqlite3.IntegrityError: UNIQUE constraint failed: experiment.name


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)

  File "/nfs/staff-ssd/gaoni/repos/seml_logger/seml_logger/__init__.py", line 47, in func
    logger = Logger(

  File "/nfs/staff-ssd/gaoni/repos/seml_logger/seml_logger/logger.py", line 63, in __init__
    self.aim_run = aim.Run(repo=self.aim_repo, experiment=self.experiment)

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/aim/sdk/run.py", line 355, in __init__
    self.experiment = experiment

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/aim/sdk/run.py", line 236, in experiment
    self.props.experiment = value

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/aim/storage/structured/sql_engine/entities.py", line 168, in experiment
    session.flush()

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3444, in flush
    self._flush(objects)

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3584, in _flush
    transaction.rollback(_capture_exception=True)

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3544, in _flush
    flush_context.execute()

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(

  File "/nfs/staff-ssd/gaoni/miniconda3/envs/jax0317/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)

sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: experiment.name
[SQL: INSERT INTO experiment (uuid, name, description, is_archived, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: ('a045b2e1-181c-400a-848e-270e455a7660', '<collection>', None, 0, '2023-01-20 08:26:28.127075', '2023-01-20 08:26:28.127080')]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

**Comment by mihran113** [comment]
Hey @n-gao! Thanks for reporting the issue.  
The fix will be shipped with the upcoming `v3.16.0` release.

**Comment by mihran113** [comment]
Hey @n-gao. The fix has been shipped with `3.16.0` release. Please have a look, and let me know if everything works as expected.

**Comment by gorarakelyan** [comment]
Closing the issue, as the fix has been shipped. @n-gao pls feel free to re-open this if the there are still any issues.
