### ISSUE TITLE
errror in aimup 

### ISSUE THREAD

**Issue by amarazad** [aimhubio/aim#2715]
When I run `aim up`, i get the following error:
```
aim up --host $(hostname -f) --port 6006 --repo test
Traceback (most recent call last):
  File "./anaconda3/envs/py39_trl/bin/aim", line 5, in <module>
    from aim.cli.cli import cli_entry_point
  File "./anaconda3/envs/py39_trl/lib/python3.9/site-packages/aim/__init__.py", line 1, in <module>
    import aimrocks
  File "./anaconda3/envs/py39_trl/lib/python3.9/site-packages/aimrocks/__init__.py", line 1, in <module>
    from .lib_rocksdb import *
ImportError: /opt/share/gcc-5.4.0/x86_64/lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./data/
trl/lib/python3.9/site-packages/aimrocks/librocksdb.so)
```
Any suggesiton ?

**Comment by alberttorosyan** [comment]
Hey @amarazad!
In order to debug this issue, we'll need additional information about the environment you are using.
Could you please share:
- Aim version
- OS version
- Version of `libstdc` library
- Python version

Any additional information about the environment, as well as `pip install aim` terminal output might be helpful.

**Comment by amarazad** [comment]
Hi @alberttorosyan , Sure Please find the details below.
