### ISSUE TITLE
Aim init fails after fresh install

### ISSUE THREAD

**Issue by Tomakko** [aimhubio/aim#2846]
Hi,

i installed aim via pip. When i try to initialize a new aim repo via `aim init` while i am in the directory `nf_registration,` i get the following error message.:

```
  FAILED: Path doesn't exist: '***/nf_registration/storage/migrations'.  Please use the 'init' command to create a new scripts folder.
Traceback (most recent call last):
  File "***/nf_registration/venv/bin/aim", line 8, in <module>
    sys.exit(cli_entry_point())
  File "***/nf_registration/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "***/nf_registration/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "***/nf_registration/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "***/nf_registration/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "***/nf_registration/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "***/nf_registration/venv/lib/python3.8/site-packages/aim/cli/init/commands.py", line 35, in init
    repo = Repo.from_path(repo_path, init=True)
  File "***/nf_registration/venv/lib/python3.8/site-packages/aim/sdk/repo.py", line 208, in from_path
    repo = Repo(path, read_only=read_only, init=init)
  File "***/nf_registration/venv/lib/python3.8/site-packages/aim/sdk/repo.py", line 151, in __init__
    self.structured_db.run_upgrades()
  File "***/nf_registration/venv/lib/python3.8/site-packages/aim/storage/structured/db.py", line 94, in run_upgrades
    upgrade_database(self.db_url)
  File "***/nf_registration/venv/lib/python3.8/site-packages/aim/storage/migrations/utils.py", line 28, in upgrade_database
    raise subprocess.SubprocessError(f'Database upgrade failed with exit code {exit_code}')
subprocess.SubprocessError: Database upgrade failed with exit code 255
```

I am clueless how to solve this issue. Can anyone point me in the right direction?

**Comment by alberttorosyan** [comment]
Hey @Tomakko! May I ask you to check the version of `sqlalchemy`?

**Comment by Tomakko** [comment]
Hi @alberttorosyan ,

i got SQLAlchemy 1.4.48

**Comment by Tomakko** [comment]
My bad..in the same directory where I wanted to do `aim init`, i had my test script named `aim.py`. Apparently, there was a name clash. Renaming my test script solved the issue for me and i can now go ahead exploring aim.
