### ISSUE TITLE
Missing .ldb file when closing a run

### ISSUE THREAD

**Issue by jennifer12121** [aimhubio/aim#2914]
## 🐛 Bug

When I run `aim runs close <hash>` I receive the following error:

`Closing runs:   0%|                                                                                       | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/aim", line 8, in <module>
    sys.exit(cli_entry_point())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/aim/cli/runs/commands.py", line 159, in close_runs
    for _ in tqdm.tqdm(
  File "/usr/local/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/site-packages/aim/sdk/repo.py", line 974, in _close_run
    index_manager.index(run_hash)
  File "/usr/local/lib/python3.8/site-packages/aim/sdk/index_manager.py", line 174, in index
    meta_run_tree.finalize(index=index)
  File "aim/storage/containertreeview.py", line 30, in aim.storage.containertreeview.ContainerTreeView.finalize
  File "aim/storage/prefixview.py", line 66, in aim.storage.prefixview.PrefixView.finalize
  File "aim/storage/rockscontainer.pyx", line 165, in aim.storage.rockscontainer.RocksContainer.finalize
  File "aim/storage/rockscontainer.pyx", line 413, in aim.storage.rockscontainer.RocksContainer.items
  File "aim/storage/rockscontainer.pyx", line 593, in aim.storage.rockscontainer.RocksContainerItemsIterator.__init__
  File "src/aimrocks/lib_rocksdb.pyx", line 2338, in aimrocks.lib_rocksdb.BaseIterator.seek
  File "src/aimrocks/lib_rocksdb.pyx", line 2342, in aimrocks.lib_rocksdb.BaseIterator.seek
  File "src/aimrocks/lib_rocksdb.pyx", line 89, in aimrocks.lib_rocksdb.check_status
aimrocks.errors.RocksIOError: b'IO error: No such file or directory: While open a file for random read: /aim/.aim/meta/chunks/59f8474b38c647b4acf741d4/000512.ldb: No such file or directory'`

I checked in that directory and the .ldb file does not exist. There are also no other .ldb files for other run hashes. How do I replace them?

### To reproduce

Through a new terminal window, run the following:

`cd aim`

`aim runs close <hash_of_run>`

### Expected behavior

Normally, the run would close out.

### Environment

- Aim Version (3.17.4)
- OS (e.g., Linux)

**Comment by mihran113** [comment]
Hey @jennifer12121! This error can occur when the  process is killed and the `rocksdb` is corrupted due to some write operation being in the middle of execution. So the problem isn't in `close` command itself. Can I ask you to provide some more details about the `Run` object creation/stoping procedure?

Also regarding the `.ldb` files, that's `rocksdb` specific error, when it can't find `.sst` files it starts to search also for `.ldb` files.

**Comment by jennifer12121** [comment]
Hi @mihran113 ! Thank you for that feedback. I'll look more into how to close out write operations for `rocksdb`. 

Would you be able to explain a bit more about what information you are looking for from the `Run` object? So far, I've tried connecting through the CLI and through the SDK to close the run. For the CLI, I ran `aim runs close 59f8474b38c647b4acf741d4` and through the SDK, I ran:

```
import aim
run = aim.Run(run_hash = 59f8474b38c647b4acf741d4, repo = <repo_url>)
run.close()
```

Through the CLI, I received the error I posted and through the SDK, no error was thrown, but when I ran `repo.list_active_runs()`, the hash number was still present.

**Comment by mihran113** [comment]
I was looking for a bit more information on how the run was created and if that process was killed with `SIGKILL` or `SIGTERM` signals. 
For ex. there's also a similar issue when concurrent runs are being created via `slurm`: 
https://github.com/aimhubio/aim/issues/2869
