### ISSUE TITLE
A bug occurs when converting from mlflow to aim.

### ISSUE THREAD

**Issue by Mai0313** [aimhubio/aim#2984]
## 🐛 Bug

Due to mlflow update [PR#6171](https://github.com/mlflow/mlflow/pull/6171), list_experiments has been replaced with search_experiments; it would be great if you guys replace it.
- [src/aimcore/cli/convert/processors/mlflow.py](https://github.com/aimhubio/aim/blob/1737b2d3573793ad30287d9335952ae7ce58a067/src/aimcore/cli/convert/processors/mlflow.py#L46)

### To reproduce

```bash
aim convert mlflow --tracking_uri 'path/to/folder/mlruns'
```

### Expected behavior

Original error code:
```
(torch2) -$ aim convert mlflow --tracking_uri 'path/to/folder/mlruns'
Traceback (most recent call last):
  File "/home/mtk30765/.conda/envs/torch2/bin/aim", line 8, in <module>
    sys.exit(cli_entry_point())
  File "/home/mtk30765/.conda/envs/torch2/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/mtk30765/.conda/envs/torch2/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/mtk30765/.conda/envs/torch2/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mtk30765/.conda/envs/torch2/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mtk30765/.conda/envs/torch2/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mtk30765/.conda/envs/torch2/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/mtk30765/.conda/envs/torch2/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mtk30765/.conda/envs/torch2/lib/python3.9/site-packages/aim/cli/convert/commands.py", line 66, in convert_mlflow
    parse_mlflow_logs(repo_inst, tracking_uri, **kwargs)
  File "/home/mtk30765/.conda/envs/torch2/lib/python3.9/site-packages/aim/cli/convert/processors/mlflow.py", line 46, in parse_mlflow_logs
    experiments = client.list_experiments()
AttributeError: 'MlflowClient' object has no attribute 'list_experiments'
```

Once you replace `list_experiments` to `search_experiments`, it will run perfectly.

### Environment

- Aim Version (e.g., 3.0.1): 3.17.5
- MLflow: 2.5.0
- Python version: 3.9.15
- pip version: 23.2.1
- OS (e.g., Linux): Linux Ubuntu 18.04.6 LTS x86_64

### Additional context

I can create a PR if you guys want me to do so, or whatever you guys like.

**Comment by TimelyToga** [comment]
It seems that the source branch on the pull request has been closed? I have added a new branch for this commit as seen here: https://github.com/TimelyToga/aim/commit/4b3b96eb86712781b7597f0f6b006877393a2155

I have not been able to test this locally as I am getting [build errors as seen in this gist](https://gist.github.com/TimelyToga/2b1feddd99eea6a856d439e808e3309d)

**Comment by jaredxfeng** [comment]
Bug is still here in 2026.

Aim Version: 3.29.1
MLflow: 3.11.1
Python version: 3.12.13
pip version: 26.0.1
OS: Arch Linux x86_64
