### ISSUE TITLE
`aim migrate` "Cannot track value ... of type .... Type is not supported.

### ISSUE THREAD

**Issue by YodaEmbedding** [aimhubio/aim#3019]
## 🐛 Bug

Attempting to migrate a repo gives:

```python-traceback
λ aim migrate --repo /mnt/data/data/aim/pc-mordor/main
This command will convert Aim Runs at '/mnt/data/data/aim/pc-mordor/main' to a new format. This might take a while. Would you like to continue? [y/N]: y
Failed to migrate Aim repo '/mnt/data/data/aim/pc-mordor/main'. Reason: Cannot track value '[17.390951]' of type <class 'list'>. Type is not supported..
Old repository backup is available at '/mnt/data/data/aim/pc-mordor/main/.aim_v3'.
Traceback (most recent call last):
  File "/home/mulhaq/.local/bin_python/aim", line 8, in <module>
    sys.exit(cli_entry_point())
             ^^^^^^^^^^^^^^^^^
  File "/home/mulhaq/.cache/pypoetry/virtualenvs/default-X4z3tkVa-py3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mulhaq/.cache/pypoetry/virtualenvs/default-X4z3tkVa-py3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/mulhaq/.cache/pypoetry/virtualenvs/default-X4z3tkVa-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mulhaq/.cache/pypoetry/virtualenvs/default-X4z3tkVa-py3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mulhaq/.cache/pypoetry/virtualenvs/default-X4z3tkVa-py3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mulhaq/.cache/pypoetry/virtualenvs/default-X4z3tkVa-py3.11/lib/python3.11/site-packages/aimcore/cli/migrate/commands.py", line 35, in migrate
    utils.migrate_data_v3_v4(repo_inst, aim_v3_dir_path, run_hash=run)
  File "/home/mulhaq/.cache/pypoetry/virtualenvs/default-X4z3tkVa-py3.11/lib/python3.11/site-packages/aimcore/cli/migrate/utils.py", line 186, in migrate_data_v3_v4
    migrate_single_run(repo, v3_repo_path, run_hash=run_hash, run_data=runs_data.get(run_hash))
  File "/home/mulhaq/.cache/pypoetry/virtualenvs/default-X4z3tkVa-py3.11/lib/python3.11/site-packages/aimcore/cli/migrate/utils.py", line 125, in migrate_single_run
    migrate_v1_sequence_data(
  File "/home/mulhaq/.cache/pypoetry/virtualenvs/default-X4z3tkVa-py3.11/lib/python3.11/site-packages/aimcore/cli/migrate/utils.py", line 71, in migrate_v1_sequence_data
    seq.track(value, step=step, epoch=epoch, time=time)
  File "/home/mulhaq/.cache/pypoetry/virtualenvs/default-X4z3tkVa-py3.11/lib/python3.11/site-packages/aim/_sdk/sequence.py", line 221, in track
    raise ValueError(f'Cannot track value \'{value}\' of type {type(value)}. Type is not supported.')
ValueError: Cannot track value '[17.390951]' of type <class 'list'>. Type is not supported.
```

### To reproduce

Log a sequence value of type `list` in v3. Then migrate to v4.

### Expected behavior

Successful migration, or perhaps "Warning: could not migrate [...]; skipping sequence [...] for run hash [...]."

### Environment

- Aim Version 4.0.0
- Python version 3.11
- pip version 23.2.1
- OS Arch Linux
- Any other relevant information

### Additional context

N/A.

**Comment by alberttorosyan** [comment]
Hey @YodaEmbedding! Thanks for reporting this issue. Good to know you are trying the migrate command 🙌 

For this particular case, IMHO the list with a single float value should be accepted. For a more generic scenario, the data still should be migrated, though not as a Metric or any other specific type, but just as a generic Sequence.

Please let me know if you have any comments/additions.
