### ISSUE TITLE
Random run initialization error

### ISSUE THREAD

**Issue by Luca-DTU** [aimhubio/aim#3057]
## 🐛 Bug
Sometimes when setting up a run I get the following error
"TypeError: DBAPIError.__init__() missing 2 required positional arguments: 'params' and 'orig'"
this arises from calling 
run = Run(repo=repo, experiment=experiment, log_system_params=True)
### To reproduce
It happens when starting multiple parallel runs on the same repository in ARGO. Out of 100 pods, maybe a couple will show this error.

### Environment

aim==3.17.5
python:3.10
argo-workflows==6.3.5
hera==5.4.1

**Comment by alberttorosyan** [comment]
Hey @Luca-DTU! Could you please share the full error stack-trace? That would help to understand the root cause of the issue.

**Comment by Luca-DTU** [comment]
Hi, 
Here it is in one example:

Traceback (most recent call last):
  File "/argo/staging/script", line 17, in <module>
    run = Run(repo=repo_name, experiment=experiment_name, log_system_params=True)
  File "/usr/local/lib/python3.10/site-packages/aim/ext/exception_resistant.py", line 70, in wrapper
    _SafeModeConfig.exception_callback(e, func)
  File "/usr/local/lib/python3.10/site-packages/aim/ext/exception_resistant.py", line 47, in reraise_exception
    raise e
  File "/usr/local/lib/python3.10/site-packages/aim/ext/exception_resistant.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aim/sdk/run.py", line 828, in __init__
    super().__init__(run_hash, repo=repo, read_only=read_only, experiment=experiment, force_resume=force_resume)
  File "/usr/local/lib/python3.10/site-packages/aim/sdk/run.py", line 325, in __init__
    self.props
  File "/usr/local/lib/python3.10/site-packages/aim/sdk/run.py", line 440, in props
    self._props = self.repo.request_props(self.hash, self.read_only)
  File "/usr/local/lib/python3.10/site-packages/aim/sdk/repo.py", line 354, in request_props
    return StructuredRunProxy(self._client, hash_, read_only, created_at)
  File "/usr/local/lib/python3.10/site-packages/aim/storage/structured/proxy.py", line 31, in __init__
    handler = self._rpc_client.get_resource_handler(self, self.resource_type, args=self.init_args)
  File "/usr/local/lib/python3.10/site-packages/aim/ext/transport/client.py", line 225, in get_resource_handler
    raise_exception(response.exception)
  File "/usr/local/lib/python3.10/site-packages/aim/ext/transport/message_utils.py", line 76, in raise_exception
    raise exception(*args) if args else exception()
TypeError: DBAPIError.__init__() missing 2 required positional arguments: 'params' and 'orig'

**Comment by erikdao** [comment]
@Luca-DTU This might be a bit late, but did you figure out a solution for your problem? I'm facing the same issue even though I'm using the latest version of aim `v3.23.0`
```
File "/app/<redactted>/tracking/tracker.py", line 25, in prepare_run
self.run.add_tag(tag)
File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/aim/sdk/run.py", line 246, in add_tag
return self.props.add_tag(value)
File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/aim/storage/structured/proxy.py", line 85, in add_tag
return self._rpc_client.run_instruction(self._hash, self._handler, 'add_tag', (value,))
File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/aim/ext/transport/client.py", line 244, in run_instruction
return self._run_read_instructions(queue_id, resource, method, args)
File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/aim/ext/transport/client.py", line 261, in _run_read_instructions
raise_exception(response.json().get('exception'))
File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/aim/ext/transport/message_utils.py", line 70, in raise_exception
raise exception(*args) if args else exception()
TypeError: DBAPIError.__init__() missing 2 required positional arguments: 'params' and 'orig'
```

cc @alberttorosyan

**Comment by hstojic** [comment]
we have been seeing this one often, for now we simply avoid using tags...

**Comment by qzed** [comment]
This seems to be related to #3216 and #3277. The exception is raised in

https://github.com/aimhubio/aim/blob/eba27a9260d033810d7d4ddbebebe2fb0be81fd0/aim/ext/transport/message_utils.py#L66-L70

If I print `server_exception`, I get

```
{'module_name': 'sqlalchemy.exc', 'class_name': 'IntegrityError', 'args': '["(sqlite3.IntegrityError) UNIQUE constraint failed: run_tag.run_id, run_tag.tag_id"]'}
```

So it tries to create a `sqlalchemy.exc.IntegrityError`, but fails. `IntegrityError` is derived from `DBAPIError`, which requires the `statement`, `params`, and `orig` as arguments in its `__init__()`. But there is only one argument provided (`statement`), hence the `TypeError`.

The actual exception it tries to raise looks similar to the one from #3277. The symptoms just seem different because a) we're logging to a remote server and not in the current process itself and b) we hit another bug along the line.

Fyi, my aim version is v3.27.0 on both server and logging client.

**Comment by iwishiwasaneagle** [comment]
I have been experiencing this issue as well. It seems to occur after a run crashes and then the subsequent run raises this error. Using the web interface or any of the aim CLI commands works fine during all of this.

**Comment by qzed** [comment]
I'm using the following as a workaround for adding tags. So far it seems to do it's job.
```python
tags = ...
tags = set(tags) - set(logger.experiment.tags)
for tag in tags:
     logger.experiment.add_tag(tag)
```
Note: I'm using the PyTorch Lightning logger, but it should be easy to adapt this. I think `logger.experiment` would just be your standard Aim `Run`.

I do get some other occasional errors though, but I think those are unrelated and only appear when I resume a run.
