### ISSUE TITLE
HTTP Transport commit is creating issue to init repo

### ISSUE THREAD

**Issue by Sharathmk99** [aimhubio/aim#3109]
### To reproduce

HTTP transport for remote tracking is very cool, tried to init repo using master, but looks like we still have some code related to proto. Under aim/cli/upgrade/_legacy_repo we still have proto related code base so it's breaking to build,

```
Traceback (most recent call last):
  File "/usr/local/bin/aim", line 5, in <module>
    from aim.cli.cli import cli_entry_point
  File "/usr/local/lib/python3.9/site-packages/aim/cli/cli.py", line 12, in <module>
    from aim.cli.storage import commands as storage_commands
  File "/usr/local/lib/python3.9/site-packages/aim/cli/storage/commands.py", line 6, in <module>
    from aim.cli.upgrade.utils import convert_2to3
  File "/usr/local/lib/python3.9/site-packages/aim/cli/upgrade/utils.py", line 6, in <module>
    from aim.cli.upgrade._legacy_repo import (
  File "/usr/local/lib/python3.9/site-packages/aim/cli/upgrade/_legacy_repo/__init__.py", line 3, in <module>
    from aim.cli.upgrade._legacy_repo.metric_artifact import deserialize_pb
  File "/usr/local/lib/python3.9/site-packages/aim/cli/upgrade/_legacy_repo/metric_artifact.py", line 1, in <module>
    from aim.cli.upgrade._legacy_repo.proto.base_pb2 import BaseRecord
  File "/usr/local/lib/python3.9/site-packages/aim/cli/upgrade/_legacy_repo/proto/base_pb2.py", line 1, in <module>
    import google.protobuf
ModuleNotFoundError: No module named 'google.protobuf'
```

@mihran113 should we remove code related to legacy upgrade?
Thanks

### Environment

- Aim Version (e.g., 3.0.1)
- Python version
- pip version
- OS (e.g., Linux)
- Any other relevant information

**Comment by mihran113** [comment]
Hey @Sharathmk99! Thanks a lot for reporting! I guess it's time to remove the 2to3 upgrade command, it's not worth keeping the protobuf as a dependency only for that.
