### ISSUE TITLE
Failed to execute 'json' on 'Response': body stream already read

### ISSUE THREAD

**Issue by jennifer12121** [aimhubio/aim#3151]
## 🐛 Bug

Runs become hung in the in progress state and an error message flashes on the side "Failed to execute 'json' on 'Response': body stream already read". When this happens, the run is not able to be closed or moved to a closed state. 

Additionally, from the terminal, when trying to run `aim runs close hash` an error message appears, so the runs are not able to be closed through the sdk or the cli. 

`Traceback (most recent call last):
  File "aim/storage/treeutils.pyx", line 112, in aim.storage.treeutils.iter_fold_tree
  File "aim/storage/treeutils.pyx", line 201, in aim.storage.treeutils.DecodePathsVals.__next__
  File "aim/storage/treeutils.pyx", line 214, in aim.storage.treeutils.DecodePathsVals._next
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aim/storage/containertreeview.py", line 71, in aim.storage.containertreeview.ContainerTreeView.collect
  File "aim/storage/treeutils.pyx", line 270, in aim.storage.treeutils.decode_tree
  File "aim/storage/treeutils.pyx", line 95, in aim.storage.treeutils.fold_tree
  File "aim/storage/treeutils.pyx", line 124, in iter_fold_tree
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/aim", line 8, in <module>
    sys.exit(cli_entry_point())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/aim/cli/runs/commands.py", line 159, in close_runs
    for _ in tqdm.tqdm(
  File "/usr/local/lib/python3.8/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/site-packages/aim/sdk/repo.py", line 976, in _close_run
    index_manager.index(run_hash)
  File "/usr/local/lib/python3.8/site-packages/aim/sdk/index_manager.py", line 175, in index
    if meta_run_tree['end_time'] is None:
  File "aim/storage/treeview.py", line 51, in aim.storage.treeview.TreeView.__getitem__
  File "aim/storage/containertreeview.py", line 73, in aim.storage.containertreeview.ContainerTreeView.collect
KeyError: "No key ('end_time',) is present."`

### To reproduce

Attempt to track multiple runs to Aim. They will not close out and will hang in progress. 

### Expected behavior

It is expected to close the runs either upon failure or upon completion.

### Environment

- Aim Version 3.19.2

**Comment by jennifer12121** [comment]
Upgrading to 3.19.3 resolved this.

**Comment by HarikrishnanBalagopal** [comment]
```
Failed to execute 'json' on 'Response': body stream already read
```

This issue is still happening in
```
# aim version
Aim v3.26.1
```

**Comment by ChrisMythos** [comment]
I have a similar issue where some runs pop in and out of fished and running. Sometimes the error Failed to execute 'json' on 'Response': body stream already read comes up and sometimes it shows the metrics, very weird indeed. 
Im on version 3.29.1

**Comment by eagomez2** [comment]
> I have a similar issue where some runs pop in and out of fished and running. Sometimes the error Failed to execute 'json' on 'Response': body stream already read comes up and sometimes it shows the metrics, very weird indeed. Im on version 3.29.1

Same as you and also using the same version. Are there any solutions to this?

**Comment by ChrisMythos** [comment]
@eagomez2 My workaround was to reindex the runs (aim storage reindex). This made sure that non-active runs are marked as finished and won't pop in and out. For the ones running this seems to help as well, but you should disable live indexing (I think this was or is the issue)
I hope this help a little bit, maybe with a newer version they'll fix it :)

Best regards
Chris

**Comment by eagomez2** [comment]
Thank you very much @ChrisMythos for your answer. With live indexing do you mean the "Live Update" toggle in the UI or are there any other sources of live indexing I may be missing?

**Comment by ChrisMythos** [comment]
@eagomez2 Yes, that's it. It's been a while since I did my ML/AI project for my masters :)
You can reindex while a run is active, but it will only show the run until the last indexing.
I know this is not optimal but when live update is turned on I got upwards of 200 mb/s read/write on my disk, due to my extensive logging and the other issues I made the original comment about :) (maybe check if r/w that goes down when live update is disabled)

Good luck man ^^

**Comment by eagomez2** [comment]
Great, thank you very much for the details! I'll give it a try :)

Best,
Esteban

**Comment by eagomez2** [comment]
Thanks @ChrisMythos . Reindex helped, although I see myself reindex too often to be able to see logs without any errors. Was that your experience as well? It makes me think on whether there is something fundamental I am missing in my code
