### ISSUE TITLE
Importing jax causes exception that is ignored

### ISSUE THREAD

**Issue by stergiosba** [aimhubio/aim#3187]
## 🐛 Bug

As title says...here is the output:
```
Exception ignored in: <function BaseFileLock.__del__ at 0x72f373c7fbe0>
Traceback (most recent call last):
  File "/home/horclab/.cache/pypoetry/virtualenvs/gakuseirl-8CAc1Ymv-py3.10/lib/python3.10/site-packages/filelock/_api.py", line 397, in __del__
  File "/home/horclab/.cache/pypoetry/virtualenvs/gakuseirl-8CAc1Ymv-py3.10/lib/python3.10/site-packages/filelock/_api.py", line 364, in release
  File "/usr/lib/python3.10/logging/__init__.py", line 1464, in debug
  File "/usr/lib/python3.10/logging/__init__.py", line 1734, in isEnabledFor
TypeError: 'NoneType' object is not callable

```

### To reproduce

```python
from aim import Run
import jax

# Initialize a new run
run = Run()

# Log run parameters
run["hparams"] = {
    "learning_rate": 0.001,
    "batch_size": 32,
}

# Log metrics
for i in range(10):
    run.track(i, name='loss', step=i, context={ "subset":"train" })
    run.track(i, name='acc', step=i, context={ "subset":"train" })

```

### Expected behavior

Not do that

### Environment

- Aim Version: 3.22
- Python version: 3.10
- pip version: 24.1.2
- OS (e.g., Linux): Linux Ubuntu 22.04 LTS
- Any other relevant information

### Additional context
-

**Comment by stergiosba** [comment]
Since the exception is ignored the experiments runs and is recorded, however is there a way to fix this?

**Comment by stergiosba** [comment]
Everything works in a fresh virtual environment. Very strange.

**Comment by VolodyaCO** [comment]
Same here!
