### ISSUE TITLE
Image Explorer: Something went wrong

### ISSUE THREAD

**Issue by Engrammae** [aimhubio/aim#3219]
### Something went wrong
![aim_something_went_wrong](https://github.com/user-attachments/assets/dd7be2bb-eedf-4c59-a6ca-f980b8a9586e)
Trying to view my tracked images in the image explorer. The runs match the query and I  I can normally view the tracked images when inspecting a single run in the Run explorer. 
Running `aim up --log-level DEBUG --repo=.` lists me the query 
```
INFO:     127.0.0.1:50314 - "GET /api/runs/search/images?q=%28%28images.name+%3D%3D+%22Generated+Trajectory%22%29%29&record_range=25%3A2001&index_range=0%3A1&record_density=50&index_density=1 HTTP/1.1" 200 OK
```

### To reproduce

I logged my experiments through the [julia-wrapper](https://github.com/aimhubio/Aim.jl) and everything worked as expected. I could view the images in the image explorer. Overnight it somehow crashed. Restarting the UI did not help, also `aim storage reindex`, `aim storage prune` and `aim runs close` had no effect. I tried Chrome and Firefox. I don't know at what point it went south and thus have no minimal working example.

### Expected behavior

The images are shown in the image explorer.

### Environment

- Aim Version (v3.24.0)
- Python version (Python 3.11.6)
- pip version 24.0
- OS  Ubuntu 22.04.4
- Chrome version 128.0.6613.84
- Firefox version 129.0.2

### Additional context

I stumbled upon #2627 but don't know whether its related. I don't know where to look exactly within chrome or firefox but chrome lists me these errors:
```
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'content')
    at onActivePointChange (imagesExploreAppModel.ts:1192:15)
    at MediaPanel.tsx:100:11
    at MediaPanel.tsx:112:7
    at Object.onListScroll [as onScroll] (MediaPanel.tsx:242:5)
    at t.<anonymous> (createListComponent.js:404:22)
    at t._callOnScroll (memoize-one.esm.js:40:31)
    at push.C.n._callPropsCallbacks (createListComponent.js:436:14)
    at push.C.n.componentDidMount (createListComponent.js:245:12)
    at pc (react-dom.production.min.js:219:411)
    at Tu (react-dom.production.min.js:259:160)

imagesExploreAppModel.ts:1192 Uncaught TypeError: Cannot read properties of undefined (reading 'content')
    at onActivePointChange (imagesExploreAppModel.ts:1192:15)
    at MediaPanel.tsx:100:11
    at MediaPanel.tsx:112:7
    at MediaPanel.tsx:140:15
``` 
This had happened to me once and I just started a repository. but  this isn't an option on the long run. Any advice is welcomed!

**Comment by Roman223** [comment]
The same to me. I think the reason for me is that I killed aim by process id, when terminal with was accidentally closed.
